__all__ = (
    "ACTION_SQL",
    "abonent",
    "ads",
    "attributes",
    "auto_payment",
    "byt",
    "core",
    "crm",
    "dt_cache",
    "elements",
    "faq",
    "generic",
    "ls_generic",
    "ls_management",
    "ls_privileges",
    "metadata",
    "multiple_payment",
    "other",
    "paid_services",
    "prepay_params",
    "privileges_avail",
    "profile",
    "specific",
    "subscriber",
    "subscription",
    "view",
)

ACTION_SQL = "sql"
